# Generated by Django 5.1.7 on 2025-03-27 07:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('model', 'Модель техники'), ('engine', 'Модель двигателя'), ('transmission', 'Модель трансмиссии'), ('axle', 'Модель моста'), ('managed_axle', 'Модель управляемого моста'), ('TO', 'Вид ТО'), ('to_organization', 'Организация, проводившая ТО'), ('failure_node', 'Узел отказа'), ('recovery_method', 'Способ восстановления')], max_length=50, verbose_name='Справочник')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Пользователь', max_length=255, verbose_name='Наименование компании')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя менеджера')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ООО Сервис', max_length=255, verbose_name='Наименование компании')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сервисная компания',
                'verbose_name_plural': 'Сервисные компании',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='Зав. № машины')),
                ('serial_engine', models.CharField(max_length=255, verbose_name='Зав. № двигателя')),
                ('serial_transmission', models.CharField(max_length=255, verbose_name='Зав. № трансмиссии')),
                ('serial_axle', models.CharField(max_length=255, verbose_name='Зав. № ведущего моста')),
                ('serial_man_axle', models.CharField(max_length=255, verbose_name='Зав. № управляемого моста')),
                ('contract_number_data', models.CharField(max_length=255, verbose_name='Договор поставки №, дата')),
                ('ship_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('recipient', models.CharField(max_length=255, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.TextField(verbose_name='Адрес поставки (эксплуатации)')),
                ('configuration', models.TextField(verbose_name='Комплектация (доп.опции)')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='silant_service.client', verbose_name='Клиент')),
                ('engine_model', models.ForeignKey(blank=True, limit_choices_to={'type': 'engine'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines_engine', to='silant_service.referenceitem', verbose_name='Модель двигателя')),
                ('model_axle', models.ForeignKey(blank=True, limit_choices_to={'type': 'axle'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines_axle', to='silant_service.referenceitem', verbose_name='Модель ведущего моста')),
                ('model_man_axle', models.ForeignKey(blank=True, limit_choices_to={'type': 'managed_axle'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines_man_axle', to='silant_service.referenceitem', verbose_name='Модель управляемого моста')),
                ('model_transmission', models.ForeignKey(blank=True, limit_choices_to={'type': 'transmission'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines_transmission', to='silant_service.referenceitem', verbose_name='Модель трансмиссии')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='silant_service.servicecompany', verbose_name='Сервисная компания')),
                ('tech_model', models.ForeignKey(blank=True, limit_choices_to={'type': 'model'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tech_model', to='silant_service.referenceitem', verbose_name='Модель техники')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='TechnicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_hours', models.FloatField(verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(max_length=100, verbose_name='№ заказ-наряда')),
                ('order_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='silant_service.servicecompany', verbose_name='Сервисная компания')),
                ('service_type', models.ForeignKey(blank=True, limit_choices_to={'type': 'TO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_type', to='silant_service.referenceitem', verbose_name='Вид ТО')),
                ('tech_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_company', to='silant_service.servicecompany', verbose_name='Организация, проводившая ТО')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='silant_service.vehicle', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'Техобслуживание',
                'verbose_name_plural': 'Техобслуживание',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='Дата отказа')),
                ('operating_hours', models.FloatField(verbose_name='Наработка, м/час')),
                ('failure_description', models.TextField(verbose_name='Описание отказа')),
                ('spare_parts', models.TextField(verbose_name='Используемые запасные части')),
                ('recovery_date', models.DateField(verbose_name='Дата восстановления')),
                ('failure_duration', models.DurationField(blank=True, null=True, verbose_name='Время простоя техники')),
                ('failure_node', models.ForeignKey(blank=True, limit_choices_to={'type': 'failure_node'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='failure_nodes', to='silant_service.referenceitem', verbose_name='Узел отказа')),
                ('recovery_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_methods', to='silant_service.referenceitem', verbose_name='Способ восстановления')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint', to='silant_service.vehicle', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
            },
        ),
    ]
